spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.212:8848
        service: ${spring.application.name}
        username: nacos
        password: nacos
        namespace: 413386ae-22f2-4b3e-89c6-b79d3c514bb2
server:
  port: 8900
